### ISSUE TITLE
Download?

### ISSUE THREAD

**Issue by 08133** [Fs00/Scarlet-Notes#1]
Hi there! 
I am very new to Github, so I apologise for stupid questions, but how can I download and install your version of the app? Or you haven't yet released an APK installer? I wanted to try out your fork of the app but can't find any link here to the APK.

**Comment by Fs00** [comment]
Hello @08133, this isn't a stupid question at all!
It's my fault that I didn't release a downloadable version of the app yet😅
This weekend I'll provide an APK which you'll find in the Releases page. Thanks for your patience 🙏

**Comment by 08133** [comment]
Aah, ok, I am eager to try it! I liked the Scarlet app and was sad to know that it was abandoned. So I checked each fork of Scarlet Notes here. I was about to give up checking as I was going up the list, when I finally opened your fork. Good to know you are still developing it as no one else is! I will wait for the APK, no problem :)

**Comment by 08133** [comment]
Hello, @Fs00 !

**Comment by 08133** [comment]
Hello, @Fs00! Will you release an APK?. Sorry to bother you, but you said last weekend.

**Comment by Fs00** [comment]
It's coming, I didn't forget about it! Sorry for the delay, I'm ironing out a few more issues before the release.
The APK will be out today or tomorrow at worst. Thanks for your patience 🙏

**Comment by Fs00** [comment]
@08133 Here it is! :point_right: [Scarlet_Fs00_8.0.0.zip](https://github.com/Fs00/Scarlet-Notes/files/8791584/Scarlet_Fs00_8.0.0.zip)
You just need to unzip the file and install the APK (GitHub didn't allow me to upload an APK directly).

If I (or you) don't find any severe/breaking bugs, I will create a new release tomorrow and put the same APK there. Happy testing! :wink:

**Comment by Fs00** [comment]
I've just published the same APK of the comment above as [the first release](https://github.com/Fs00/Scarlet-Notes/releases/tag/8.0.0) of this fork. Enjoy!
